// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwPlV6XSmUwGJFqq1kUos40tZetMmSwzQ',
    appId: '1:703282470352:web:3f1da0787c4c8d89ef6dd5',
    messagingSenderId: '703282470352',
    projectId: 'tankfis',
    authDomain: 'tankfis.firebaseapp.com',
    databaseURL: 'https://tankfis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tankfis.appspot.com',
    measurementId: 'G-5TDX2BB4WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd7uhTjyy7jb1K2W6xGrxiNGiVP7t2cXQ',
    appId: '1:703282470352:android:a5509065834a5e7def6dd5',
    messagingSenderId: '703282470352',
    projectId: 'tankfis',
    databaseURL: 'https://tankfis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tankfis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARygO3c3TiJ1tT7QnBqASyIIJpj2phXAc',
    appId: '1:703282470352:ios:99c121c3f96e6d17ef6dd5',
    messagingSenderId: '703282470352',
    projectId: 'tankfis',
    databaseURL: 'https://tankfis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tankfis.appspot.com',
    iosClientId: '703282470352-7khs955tdrcev7t6ulrdtd3uubhdvalh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tankFish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARygO3c3TiJ1tT7QnBqASyIIJpj2phXAc',
    appId: '1:703282470352:ios:99c121c3f96e6d17ef6dd5',
    messagingSenderId: '703282470352',
    projectId: 'tankfis',
    databaseURL: 'https://tankfis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tankfis.appspot.com',
    iosClientId: '703282470352-7khs955tdrcev7t6ulrdtd3uubhdvalh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tankFish',
  );
}
