// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6kBudBuEBu-pamGPGN1juL1wcfdj2QYQ',
    appId: '1:841569680247:web:a97f3e9c70763ee4aa3f72',
    messagingSenderId: '841569680247',
    projectId: 'tankfis-backup',
    authDomain: 'tankfis-backup.firebaseapp.com',
    databaseURL: 'https://tankfis-backup-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tankfis-backup.appspot.com',
    measurementId: 'G-3SDDS7YVMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkHcFPjkcsyEgQ0QfCxee6_E8sVZgbAo',
    appId: '1:841569680247:android:6ccfb7d4401fb2aeaa3f72',
    messagingSenderId: '841569680247',
    projectId: 'tankfis-backup',
    databaseURL: 'https://tankfis-backup-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tankfis-backup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_qy6W4QHB0ZD2dhuQK5iVz_f-w0tCGc',
    appId: '1:841569680247:ios:11cf04db81a9902aaa3f72',
    messagingSenderId: '841569680247',
    projectId: 'tankfis-backup',
    databaseURL: 'https://tankfis-backup-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tankfis-backup.appspot.com',
    iosBundleId: 'com.example.tankFish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6_qy6W4QHB0ZD2dhuQK5iVz_f-w0tCGc',
    appId: '1:841569680247:ios:11cf04db81a9902aaa3f72',
    messagingSenderId: '841569680247',
    projectId: 'tankfis-backup',
    databaseURL: 'https://tankfis-backup-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tankfis-backup.appspot.com',
    iosBundleId: 'com.example.tankFish',
  );
}
